export const contact = {
  phone: "+1 609 436 0132",
  phoneHref: "tel:+16094360132",
  email: "hello@72degreeseast.com",
  address: "1800 E State St Suite 168C, Hamilton Twp, NJ 08609",
};

export const services = [
  {
    slug: "3pl-export-logistics",
    title: "3PL & Export Logistics",
    eyebrow: "From receipt to international dispatch",
    summary: "End-to-end 3PL support including shipment intake, small parcel receiving, packing, consolidation, and export dispatch.",
    detail: "We receive and process small parcels, organize inventory for shipment readiness, perform packing and consolidation, and coordinate export movement with clear execution updates.",
    image: "/assets/photos/warehouse-2048x1365.jpg",
    steps: ["Inbound receiving", "Packing & consolidation", "Export dispatch"],
  },
  {
    slug: "food-and-beverage",
    title: "Food & Beverage",
    eyebrow: "Consistent supply across borders",
    summary: "Distribution, import, and export support for superior quality food and non-food products.",
    detail: "We support sourcing, procurement coordination, and cross-border distribution with practical execution for consistent supply and market coverage.",
    image: "/assets/photos/service-food.jpg",
  },
  {
    slug: "health-and-beauty",
    title: "Health & Beauty",
    eyebrow: "Quality-led category operations",
    summary: "Global sourcing and distribution support for top-tier health and beauty products.",
    detail: "From product sourcing to delivery coordination, we support quality-driven operations for health and beauty categories across target markets.",
    image: "/assets/photos/service-beauty.jpg",
  },
  {
    slug: "outdoor-sports",
    title: "Outdoor Sports",
    eyebrow: "Specialty products, global reach",
    summary: "Supply support with a focus on hunting, fishing, and premium knife categories.",
    detail: "We support product category planning, supplier coordination, and efficient delivery for specialty outdoor markets.",
    image: "/assets/photos/fishing-1.jpg",
    gallery: ["/assets/photos/knife-1.jpg"],
  },
  {
    slug: "pet-supplies",
    title: "Pet Supplies",
    eyebrow: "Dependable category distribution",
    summary: "Distribution services across products for furry, feathered, and finned companions.",
    detail: "We help with category sourcing, product movement, and operational coordination for stable pet-supplies distribution.",
    image: "/assets/photos/pet-supplies-1.jpg",
  },
  {
    slug: "quality-control-services",
    title: "Quality Control",
    eyebrow: "Standards built into every step",
    summary: "Inspection-based quality assurance to improve compliance and operational consistency.",
    detail: "We help teams identify defects, maintain compliance, and improve consistency using structured checks and measurable quality standards.",
    image: "/assets/photos/service-qc.webp",
  },
  {
    slug: "packing-services",
    title: "Packing Services",
    eyebrow: "Ready for the next mile",
    summary: "Professional packing support for manufacturing, warehousing, and logistics operations.",
    detail: "Our teams handle products carefully and pack according to quality and delivery requirements so shipments move safely and efficiently.",
    image: "/assets/photos/package-1.jpg",
    gallery: ["/assets/photos/package-2.jpg", "/assets/photos/package-3.jpg"],
  },
  {
    slug: "data-entry-services",
    title: "Data Entry Services",
    eyebrow: "Accurate data, smoother operations",
    summary: "Accurate, efficient, and reliable data management for business workflows.",
    detail: "From document digitization to high-volume information processing, we prioritize precision, confidentiality, and speed.",
    image: "/assets/photos/data-entry-1.jpg",
    gallery: ["/assets/photos/data-entry-2.jpg"],
  },
];
